### ISSUE TITLE
Unavailability of vmlinux

### ISSUE THREAD

**Issue by griffinevans** [lwfinger/rtw89#145]
I bought a new laptop and installed Linux Mint Edge with kernel version 5.13. The laptop has a wifi card with chip ID 10ec:b852. When I followed the directions here, I had errors about the unavailability of vmlinux. 

```
$ make
make -C /lib/modules/5.13.0-25-generic/build M=/home/username/rtw89 modules
make[1]: Entering directory '/usr/src/linux-headers-5.13.0-25-generic'
  CC [M]  /home/username/rtw89/core.o
  CC [M]  /home/username/rtw89/debug.o
  CC [M]  /home/username/rtw89/mac80211.o
  CC [M]  /home/username/rtw89/mac.o
  CC [M]  /home/username/rtw89/phy.o
  CC [M]  /home/username/rtw89/fw.o
  CC [M]  /home/username/rtw89/rtw8852a.o
  CC [M]  /home/username/rtw89/rtw8852a_table.o
  CC [M]  /home/username/rtw89/rtw8852a_rfk.o
  CC [M]  /home/username/rtw89/rtw8852a_rfk_table.o
  CC [M]  /home/username/rtw89/cam.o
  CC [M]  /home/username/rtw89/efuse.o
  CC [M]  /home/username/rtw89/regd.o
  CC [M]  /home/username/rtw89/coex.o
  CC [M]  /home/username/rtw89/ps.o
  CC [M]  /home/username/rtw89/sar.o
  CC [M]  /home/username/rtw89/ser.o
  CC [M]  /home/username/rtw89/util.o
  LD [M]  /home/username/rtw89/rtw89core.o
  CC [M]  /home/username/rtw89/pci.o
  LD [M]  /home/username/rtw89/rtw89pci.o
  MODPOST /home/username/rtw89/Module.symvers
  CC [M]  /home/username/rtw89/rtw89core.mod.o
  LD [M]  /home/username/rtw89/rtw89core.ko
  BTF [M] /home/username/rtw89/rtw89core.ko
Skipping BTF generation for /home/username/rtw89/rtw89core.ko due to unavailability of vmlinux
  CC [M]  /home/username/rtw89/rtw89pci.mod.o
  LD [M]  /home/username/rtw89/rtw89pci.ko
  BTF [M] /home/username/rtw89/rtw89pci.ko
Skipping BTF generation for /home/username/rtw89/rtw89pci.ko due to unavailability of vmlinux
make[1]: Leaving directory '/usr/src/linux-headers-5.13.0-25-generic'`
```

I didn't have any other issues, it installs without any errors and
`$ modprobe rtw89pci` & `$ modprobe rtw_8852ae` 
both run without any output. The wifi does not work. Do you know what the problem is?

**Comment by lwfinger** [comment]
That is not an error. It merely is indicating that a certain facility is not available, mainly because you are using a pre-built kernel.

Your NIC is an rtw8852be. At the moment, rtw89 only handles rtw8852ae and rtw8852ce, with the latter still a work in progress. My contact at Realtek says their calendar calls for the rtw8852be to be done by November 2022. In the meantime, this is your lucky day!

I just pushed a driver for this device to GitHub. Clone it with 'git clone git@github.com:lwfinger/rtw8852be.git'.

This driver is very rough. With kernel 5.19-rc1, the kernel is checking to ensure that things like memcpy do not overrun the destination. It turns out that in many places, this driver is writing a relatively large struct into a u32 location! I am working on cleaning up these problems, but it will take a while. Perhaps it works for you as is. My kernel complains, thus I will need to fix it, but it is available for you.
