### ISSUE TITLE
Does this follow upstream development?

### ISSUE THREAD

**Issue by CharString** [lwfinger/rtw89#157]
I see a lot of patches flying by on the [linux-wireless@vger.kernel.org](https://lore.kernel.org/linux-wireless/?q=rtw89) mailing-list that don't appear in this repo.

**Comment by lwfinger** [comment]
The code in all those patches are applied to this repo shortly after they are accepted into the wireless-next repo. You do not see then in the git log by name because it is impossible to apply then directly due to the conditional code in this repo so that the driver will build on kernels older than the current mainline version - 6.0.0-rc4 at the moment.

The merge process is as follows:
1. Prepare a difference file between the code in this repo and that in wireless-next.
2. Edit that file to remove all patch hunks that depend on kernel version.
3. Once that is done, apply that difference file as a patch.
4. Get a new difference file
5. Hand edit those places where a change in the code is intermingled with stuff that is kernel version dependent.
6. Build and test.
7. Add to this repo with subjects such as "rtw89: Update code to match that of kernel 6.0.0", or a date may be listed.
 
Note: The code here is always at least as new as the current released kernel.
