### ISSUE TITLE
dpkg buildpackage was broken after last commit when firmware bin files was removed

### ISSUE THREAD

**Issue by mandalorian-one** [lwfinger/rtw89#195]
> dpkg-buildpackage -us -uc
dh_install -prtw89-dkms *.c *.h *.bin *.md 					usr/src/rtw89-1.0.2
dh_install: warning: Cannot find (any matches for) "*.bin" (tried in ., debian/tmp)
	install -d debian/.debhelper/generated/rtw89-dkms
	install -d debian/.debhelper/generated/rtw89-firmware
dh_install: error: missing files, aborting
make[1]: *** [debian/rules:16: override_dh_auto_install] Error 255
make[1]: Leaving directory '..../rtw89'
make: *** [debian/rules:13: binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2

**Comment by lwfinger** [comment]
I do not handle any of the dkms stuff. I have fixed the rules error listed above; however, now that the firmware is coming from the distro, I do not believe that the dkms stuff should be removing the firmware. I have no idea what needs to be done to take it out. Rather than break it, I leave that part to someone that knows what they are doing.
