### ISSUE TITLE
Wifi stops working after reboot

### ISSUE THREAD

**Issue by relseirg** [lwfinger/rtw89#216]
Hi, 
is installed and added rtw_8852be on my Lenovo Thinkpad E15 (running on Ubuntu 20.04, kernel 5.15.0-58-generic) yesterday, and it worked fine. After reboot it stopped working. Tried around a little bit and did not get it running again. Here are the related syslog entries:

Jan 20 19:46:28 ThinkPad-E15-Gen-4 kernel: [  358.862149] rtw89_8852be 0000:03:00.0: Direct firmware load for rtw89/rtw8852b_fw.bin failed with error -2
Jan 20 19:46:28 ThinkPad-E15-Gen-4 kernel: [  358.862156] rtw89_8852be 0000:03:00.0: failed to early request firmware: -2
Jan 20 19:46:28 ThinkPad-E15-Gen-4 kernel: [  358.862229] rtw89_8852be 0000:03:00.0: Direct firmware load for rtw89/rtw8852b_fw.bin failed with error -2
Jan 20 19:46:28 ThinkPad-E15-Gen-4 kernel: [  358.862231] rtw89_8852be 0000:03:00.0: failed to request firmware
Jan 20 19:46:28 ThinkPad-E15-Gen-4 kernel: [  358.863979] rtw89_8852be 0000:03:00.0: failed to wait firmware completion
Jan 20 19:46:28 ThinkPad-E15-Gen-4 kernel: [  358.863983] rtw89_8852be 0000:03:00.0: failed to setup chip information
Jan 20 19:46:28 ThinkPad-E15-Gen-4 kernel: [  358.864431] rtw89_8852be: probe of 0000:03:00.0 failed with error -22

Any ideas on how to fix it? I'm sorry if I'm missing something here, I'm quite new to the linux world.

**Comment by lwfinger** [comment]
Your problem has nothing to do with a reboot. If you carefully read the log entries that you posted, the conclusion is that the firmware is not available. That is the fault of your distro, as the necessary firmware has been available in the linux-firmware repo since October.

Read that last part of README.md. It tells you how to acquire and install that firmware.
