### ISSUE TITLE
No issue - just a question

### ISSUE THREAD

**Issue by VarLad** [lwfinger/rtw89#49]
Any idea by when will it get merged into the linux kernel?

**Comment by lwfinger** [comment]
This question has been answered several times. The code is in review, but nobody is stepping up to do that job, mostly because Realtek has a reputation for writing lousy code. I do not think the current 5.88 and 5.89 drivers have this problem, but a bad reputation is hard to shake. Once rtw89 passes review, then it will be merged with wireless-testing-nest. When the next major release is near, those changes will be pushed to the feeder trees for mainline. As the driver missed kernel v5.15, the earliest would be 5.16 in about 4 months, or 5.17 in 6 months, etc.

In the interim, I am keeping this out-of-kernel repo up to date with the proposed kernel version.
